[package]
name = "sliding-blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
itertools = "0.13.0"
pathfinding = "4.10.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "example"
harness = false
